cmake_minimum_required(VERSION 3.16)
project(enpm702_cpp LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

add_compile_options(-Wall -Wextra)

add_subdirectory(src/week1)
# add_subdirectory(src/week2)
# add_subdirectory(src/week3)
# add_subdirectory(src/week4)
# add_subdirectory(src/week5)
# add_subdirectory(src/week6)
# add_subdirectory(src/week7)
# add_subdirectory(src/week8)
# add_subdirectory(src/week9)
